import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
import { v4 as uuidv4 } from "uuid";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function generateApiKey(): string {
  return `usc_live_${uuidv4().replace(/-/g, "")}`;
}

export function formatBytes(bytes: number): string {
  if (!bytes) return "0 B";
  const k = 1024;
  const sizes = ["B", "KB", "MB", "GB"];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(1))} ${sizes[i]}`;
}

export function timeAgo(date: string | Date): string {
  const diff = Date.now() - new Date(date).getTime();
  const s = Math.floor(diff / 1000);
  if (s < 60) return "just now";
  if (s < 3600) return `${Math.floor(s / 60)}m ago`;
  if (s < 86400) return `${Math.floor(s / 3600)}h ago`;
  return `${Math.floor(s / 86400)}d ago`;
}

export function jsonToCsv(data: Record<string, unknown>[]): string {
  if (!data.length) return "";
  const headers = Object.keys(data[0]);
  const rows = data.map((r) =>
    headers.map((h) => {
      const v = String(r[h] ?? "");
      return v.includes(",") || v.includes('"') ? `"${v.replace(/"/g, '""')}"` : v;
    }).join(",")
  );
  return [headers.join(","), ...rows].join("\n");
}

export function buildOpenApiSpec(projectId: string, projectName: string, baseUrl: string, schema: Record<string, unknown>[]) {
  return {
    openapi: "3.0.0",
    info: { title: `${projectName} API`, version: "1.0.0", description: `Auto-generated by Universal Scraper` },
    servers: [{ url: `${baseUrl}/api/projects/${projectId}` }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      "/data": {
        get: {
          summary: "Get all scraped data",
          parameters: [
            { name: "page", in: "query", schema: { type: "integer", default: 1 } },
            { name: "limit", in: "query", schema: { type: "integer", default: 20 } },
          ],
          responses: { "200": { description: "Paginated data" } },
        },
      },
      "/search": { get: { summary: "Search data", parameters: [{ name: "q", in: "query", required: true, schema: { type: "string" } }], responses: { "200": { description: "Results" } } } },
      "/schema": { get: { summary: "Get schema", responses: { "200": { description: "JSON schema" } } } },
      "/docs": { get: { summary: "OpenAPI spec", responses: { "200": { description: "This document" } } } },
    },
    components: {
      schemas: {
        Item: { type: "object", properties: Object.fromEntries((schema || []).map((f: Record<string, unknown>) => [f.name as string, { type: f.type as string, description: f.description as string }])) },
      },
      securitySchemes: { ApiKeyAuth: { type: "apiKey", in: "header", name: "X-API-Key" } },
    },
  };
}

// ── Built-in scraper (runs entirely on Vercel, no Python needed) ──────────────

export async function scrapeUrl(url: string): Promise<{
  json: Record<string, unknown>;
  markdown: string;
  schema: Record<string, unknown>[];
  engine: string;
  sizeBytes: number;
}> {
  const engines = [fetchWithCheerio, fetchBasic];

  for (const engine of engines) {
    try {
      return await engine(url);
    } catch {
      continue;
    }
  }
  throw new Error("All scraping engines failed");
}

async function fetchWithCheerio(url: string) {
  const { load } = await import("cheerio");

  const res = await fetch(url, {
    headers: {
      "User-Agent": "Mozilla/5.0 (compatible; UniversalScraper/1.0)",
      Accept: "text/html,application/xhtml+xml",
    },
    signal: AbortSignal.timeout(15000),
  });

  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const html = await res.text();
  const $ = load(html);

  // Remove noise
  $("script, style, nav, footer, iframe, noscript, header").remove();

  const title = $("title").text().trim() || $("h1").first().text().trim() || "Untitled";
  const description =
    $('meta[name="description"]').attr("content") ||
    $('meta[property="og:description"]').attr("content") ||
    "";
  const author =
    $('meta[name="author"]').attr("content") ||
    $('[class*="author"]').first().text().trim().slice(0, 80) ||
    "";
  const publishedDate =
    $('meta[property="article:published_time"]').attr("content") ||
    $("time").attr("datetime") ||
    "";

  const h1s: string[] = [];
  $("h1").each((_, el) => { const t = $(el).text().trim(); if (t) h1s.push(t); });

  const h2s: string[] = [];
  $("h2").each((_, el) => { const t = $(el).text().trim(); if (t && h2s.length < 15) h2s.push(t); });

  const h3s: string[] = [];
  $("h3").each((_, el) => { const t = $(el).text().trim(); if (t && h3s.length < 10) h3s.push(t); });

  const paragraphs: string[] = [];
  $("p").each((_, el) => { const t = $(el).text().trim(); if (t.length > 40 && paragraphs.length < 8) paragraphs.push(t); });

  const links: string[] = [];
  $("a[href]").each((_, el) => { const h = $(el).attr("href") || ""; if (h.startsWith("http") && links.length < 15) links.push(h); });

  const images: string[] = [];
  $("img[src]").each((_, el) => { const s = $(el).attr("src") || ""; if (s.startsWith("http") && images.length < 8) images.push(s); });

  // Price detection
  const fullText = $.root().text();
  const priceMatch = fullText.match(/[$€£¥][\d,]+\.?\d{0,2}/g);
  const prices = priceMatch
    ? [...new Set(priceMatch.map((p) => parseFloat(p.replace(/[^0-9.]/g, ""))))]
        .filter((p) => p > 0 && p < 1_000_000)
        .slice(0, 3)
    : [];

  const json: Record<string, unknown> = {
    url,
    title,
    ...(description && { description }),
    headings: { h1: h1s, h2: h2s, h3: h3s },
    content: paragraphs,
    ...(author && { author }),
    ...(publishedDate && { publishedDate }),
    ...(prices.length > 0 && { prices, primaryPrice: prices[0] }),
    links: links.slice(0, 10),
    images: images.slice(0, 5),
    scrapedAt: new Date().toISOString(),
    sourceUrl: url,
  };

  const markdown = [
    `# ${title}`,
    description ? `\n${description}` : "",
    author ? `\n**Author:** ${author}` : "",
    h2s.length ? `\n## Contents\n\n${h2s.map((h) => `- ${h}`).join("\n")}` : "",
    paragraphs.length ? `\n## Content\n\n${paragraphs.slice(0, 3).join("\n\n")}` : "",
  ].filter(Boolean).join("\n");

  const schema: Record<string, unknown>[] = [
    { name: "url", type: "url", description: "Source URL", required: true },
    { name: "title", type: "string", description: "Page title", required: true },
    { name: "description", type: "string", description: "Meta description", required: false },
    { name: "headings", type: "object", description: "H1/H2/H3 headings", required: false },
    { name: "content", type: "array", description: "Paragraphs", required: false },
    ...(author ? [{ name: "author", type: "string", description: "Author", required: false }] : []),
    ...(publishedDate ? [{ name: "publishedDate", type: "date", description: "Published date", required: false }] : []),
    ...(prices.length ? [{ name: "primaryPrice", type: "number", description: "Price", required: false }] : []),
    { name: "links", type: "array", description: "Links", required: false },
    { name: "images", type: "array", description: "Images", required: false },
    { name: "scrapedAt", type: "date", description: "Scrape timestamp", required: true },
  ];

  return { json, markdown, schema, engine: "cheerio", sizeBytes: html.length };
}

async function fetchBasic(url: string) {
  const res = await fetch(url, {
    headers: { "User-Agent": "Mozilla/5.0 (compatible; UniversalScraper/1.0)" },
    signal: AbortSignal.timeout(10000),
  });

  const html = await res.text();

  const title = (html.match(/<title[^>]*>([^<]+)<\/title>/i)?.[1] ?? "").trim();
  const description = (html.match(/<meta[^>]+name="description"[^>]+content="([^"]+)"/i)?.[1] ?? "").trim();

  const h2s = [...html.matchAll(/<h2[^>]*>([^<]+)<\/h2>/gi)].map((m) => m[1].trim()).filter(Boolean).slice(0, 10);

  const json: Record<string, unknown> = {
    url, title: title || "Untitled",
    ...(description && { description }),
    headings: { h2: h2s },
    scrapedAt: new Date().toISOString(),
    sourceUrl: url,
  };

  const schema: Record<string, unknown>[] = [
    { name: "url", type: "url", description: "Source URL", required: true },
    { name: "title", type: "string", description: "Page title", required: true },
    { name: "scrapedAt", type: "date", description: "Scrape timestamp", required: true },
  ];

  return { json, markdown: `# ${title}\n\n${description}`, schema, engine: "basic", sizeBytes: html.length };
}
